# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Lorsalio - Wallpapers, Icons
email: lorsalio7@gmail.com
description: Free downloads, wallpapers, patterns, icons. The wallpapers are created in high resolution 4K and adapted for different mobile devices. Icons are designed primarily for the Android OS, but may be suitable for other OS.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://lorsalio.github.io" # the base hostname & protocol for your site, e.g. http://example.com
imagehome: "img/imagehome.jpg"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate-v2

pagination:
  enabled: true
  per_page: 6
  permalink: "/pages/page:num/"
  title: ':title - Страница :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true


socials:
  twitter:
    url: "https://twitter.com/Lorsalio"
    icon: "twitter-ic"
  donation:
    url: "#"
    icon: "donation-ic"
  email:
    url: "mailto:lorsalio7@gmail.com"
    icon: "email-ic"

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - readme.md
  - package.json
  - package-lock.json
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

